name: Terraform CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform Formatting
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init
        continue-on-error: true

      - name: Terraform Validate
        run: terraform validate
        continue-on-error: true
